/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Food;

import java.awt.Component;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Searchbundaumamtom extends javax.swing.JFrame {

    /**
     * Creates new form Searchbundaumamtom
     */
    public Searchbundaumamtom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mua = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        themgiohang = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        mua1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        themgiohang1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        mua2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        themgiohang2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        mua3 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        themgiohang3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btntimkiem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bún đậu mắm tôm");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(560, 10, 183, 52);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bundaumamtom1.png"))); // NOI18N

        mua.setText("Buy now");
        mua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muaActionPerformed(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Bún đậu cô Ren\n305 Trường Chinh,Hoà An,Cẩm Lệ\n");
        jScrollPane3.setViewportView(jTextArea3);

        jButton3.setText("Rating");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        themgiohang.setText("Add to cart");
        themgiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themgiohangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mua)
                                    .addComponent(themgiohang))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(themgiohang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(6, 149, 260, 280);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bundaumamtom2.png"))); // NOI18N

        mua1.setText("Buy now");
        mua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mua1ActionPerformed(evt);
            }
        });

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Bún đậu A Huy\n142 Nguyễn Văn Linh,Hải Châu,Đà Nẵng\n");
        jScrollPane4.setViewportView(jTextArea4);

        jButton4.setText("Rating");

        themgiohang1.setText("Add to cart");
        themgiohang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themgiohang1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mua1))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(themgiohang1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(themgiohang1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mua1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(330, 149, 260, 290);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bundaumamtom3.png"))); // NOI18N

        mua2.setText("Buy now");
        mua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mua2ActionPerformed(evt);
            }
        });

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("Bún đậu 68\n68 Tô Hiệu,Hoà Minh,Liên Chiểu");
        jScrollPane5.setViewportView(jTextArea5);

        jButton5.setText("Rating");

        themgiohang2.setText("Add to cart");
        themgiohang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themgiohang2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(mua2))
                                    .addComponent(themgiohang2))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(themgiohang2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mua2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(680, 149, 260, 280);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bundaumamtom4.png"))); // NOI18N

        mua3.setText("Buy now");
        mua3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mua3ActionPerformed(evt);
            }
        });

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("Bún giò heo\n142 Trường Chinh,Hoà An,Cẩm Lệ\n");
        jScrollPane6.setViewportView(jTextArea6);

        jButton6.setText("Rating");

        themgiohang3.setText("Add to cart");
        themgiohang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themgiohang3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(mua3))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(themgiohang3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(themgiohang3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mua3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(1020, 149, 260, 280);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 20, 72, 23);

        btntimkiem.setText("Search");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });
        getContentPane().add(btntimkiem);
        btntimkiem.setBounds(1160, 60, 123, 39);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/giaodienfood6.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1300, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void muaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muaActionPerformed
        String quantityStr = JOptionPane.showInputDialog(this, "Nhập số lượng bạn muốn mua:");

        if (quantityStr != null && !quantityStr.trim().isEmpty()) {
            try {
                int quantity = Integer.parseInt(quantityStr);
                // Xử lý mua hàng thành công
                JOptionPane.showMessageDialog(this, "Mua thành công: " + quantity + " món " + jTextArea3.getText().split("\n")[0], "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                // Ghi vào file
                try (FileWriter writer = new FileWriter("donhang.txt", true)) {
                    writer.write("Món: " + jTextArea3.getText().split("\n")[0] + "\n");
                    writer.write("Số lượng: " + quantity + "\n");
                    writer.write("-----\n");
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn phải nhập số lượng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_muaActionPerformed

    private void themgiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themgiohangActionPerformed
        // Hiển thị thông báo
        JOptionPane.showMessageDialog(this, "Bạn đã thêm vào giỏ hàng", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        // Ghi vào file
        try (FileWriter writer = new FileWriter("giohang.txt", true)) {
            writer.write("Món: " + jTextArea3.getText().split("\n")[0] + "\n");
            writer.write("Địa chỉ: " + jTextArea3.getText().split("\n")[1] + "\n");
            writer.write("-----\n");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_themgiohangActionPerformed

    private void mua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mua1ActionPerformed

    private void themgiohang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themgiohang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_themgiohang1ActionPerformed

    private void mua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mua2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mua2ActionPerformed

    private void themgiohang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themgiohang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_themgiohang2ActionPerformed

    private void mua3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mua3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mua3ActionPerformed

    private void themgiohang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themgiohang3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_themgiohang3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Tạo và hiển thị giao diện Giaodien
        Giaodien giaodien = new Giaodien();
        giaodien.setVisible(true);
        this.dispose(); // Đóng cửa sổ hiện tại nếu cần
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
       String searchQuery = JOptionPane.showInputDialog(this, "Nhập từ khóa tìm kiếm:");
    
    try {
        if ("bún đậu mắm tôm".equalsIgnoreCase(searchQuery)) {
            new Searchbundaumamtom().setVisible(true);
            saveToFile("bún đậu mắm tôm");
        } else if ("mì cay".equalsIgnoreCase(searchQuery)) {
            new Searchmicay().setVisible(true);
            saveToFile("mì cay");
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy món ăn!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Có lỗi khi lưu vào file!", "Thông báo", JOptionPane.ERROR_MESSAGE);
    }
}

private void saveToFile(String dishName) throws IOException {
    try (FileWriter writer = new FileWriter("search_results.txt", true)) {
        writer.write("Tìm thấy món: " + dishName + "\n");
    }
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String[] comments = {
        "Bún đậu mắm tôm rất ngon! ⭐⭐⭐⭐",
        "Món này thật tuyệt vời, tôi rất thích! ⭐⭐⭐⭐",
        "Chất lượng bún đậu mắm tôm tuyệt hảo! ⭐⭐⭐⭐",
        "Giá cả hợp lý cho một món ăn ngon. ⭐⭐⭐⭐",
        "Tôi sẽ quay lại lần sau! ⭐⭐⭐⭐",
        "Có thể thêm chút nước chấm cho đậm đà hơn. ⭐⭐⭐⭐"
    };

    StringBuilder commentList = new StringBuilder("Đánh giá về món Bún Đậu Mắm Tôm:\n\n");
    List<String> likedComments = new ArrayList<>();
    List<String> dislikedComments = new ArrayList<>();

    // Tạo một JPanel để chứa bình luận và nút
    JPanel panel = new JPanel();
    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

    for (String comment : comments) {
        JCheckBox likeBox = new JCheckBox(comment); // Tạo checkbox cho mỗi bình luận
        panel.add(likeBox);
    }

    // Hiển thị hộp thoại
    int result = JOptionPane.showConfirmDialog(this, panel, "Đánh giá về món Bún Đậu Mắm Tôm", JOptionPane.OK_CANCEL_OPTION);
    
    if (result == JOptionPane.OK_OPTION) {
        for (Component comp : panel.getComponents()) {
            if (comp instanceof JCheckBox) {
                JCheckBox checkBox = (JCheckBox) comp;
                if (checkBox.isSelected()) {
                    likedComments.add(checkBox.getText());
                } else {
                    dislikedComments.add(checkBox.getText());
                }
            }
        }
        
        // Ghi vào file
        saveCommentsToFile(likedComments, dislikedComments, "comments_bundau.txt");
    }
}

private void saveCommentsToFile(List<String> likedComments, List<String> dislikedComments, String fileName) {
    try (FileWriter writer = new FileWriter(fileName, true)) {
        writer.write("Bình luận yêu thích:\n");
        for (String comment : likedComments) {
            writer.write(comment + "\n");
        }
        
        writer.write("\nBình luận không thích:\n");
        for (String comment : dislikedComments) {
            writer.write(comment + "\n");
        }
        
        writer.write("-----\n");
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Có lỗi khi lưu vào file!", "Thông báo", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searchbundaumamtom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searchbundaumamtom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searchbundaumamtom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searchbundaumamtom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searchbundaumamtom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JButton mua;
    private javax.swing.JButton mua1;
    private javax.swing.JButton mua2;
    private javax.swing.JButton mua3;
    private javax.swing.JButton themgiohang;
    private javax.swing.JButton themgiohang1;
    private javax.swing.JButton themgiohang2;
    private javax.swing.JButton themgiohang3;
    // End of variables declaration//GEN-END:variables
}
