/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FE;

import FE.Chi_Phi;
import FE.Thong_Bao;
import com.sun.jdi.connect.spi.Connection;
import java.io.IOException;
import javax.swing.JOptionPane;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DUY NGUYEN
 */
public class Chia_Se extends javax.swing.JFrame {

    /**
     * Creates new form Trip_planner
     */
    public Chia_Se() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Search and Suggest");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 140, 40));

        jButton2.setText("Notes on the trip");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 220, 180, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Khám phá thế giới, bắt đầu từ đây");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 567, 65));

        jButton3.setText("Notifications and reminders");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 180, 40));

        jButton4.setText("Schedule A Trip");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 40));

        jButton5.setText("Costing Feature");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, -1, 40));

        jButton6.setText("Vehicle Management");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 200, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TRAVEL AND MAP");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 180, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Trip Planner - Người bạn đồng hành lý tưởng cho mọi hành trình!");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 565, 81));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hãy chia sẽ trải nghiệm của bạn với chúng tôi:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 160, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 830, 280));

        jButton7.setText("Xác nhận");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 160, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tên của bạn:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gmail:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Địa điểm:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 160, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bạn hãy viết nội dung muốn chia sẽ vào ô ở dưới");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Home");
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, 100, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(1300, 700));
        jLabel6.setMinimumSize(new java.awt.Dimension(1300, 700));
        jLabel6.setPreferredSize(new java.awt.Dimension(1300, 700));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 // Tạo đối tượng JFrame mới (Len_Lich)
    Chia_Se lenLichFrame = new Chia_Se();

    // Hiển thị JFrame Len_Lich
    lenLichFrame.setVisible(true);

    // Đóng JFrame hiện tại (nếu cần)
    this.dispose();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             // Tạo đối tượng JFrame mới (Len_Lich)
    Tim_Kiem lenLichFrame = new Tim_Kiem();

    // Hiển thị JFrame Len_Lich
    lenLichFrame.setVisible(true);

    // Đóng JFrame hiện tại (nếu cần)
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       // Tạo đối tượng JFrame mới (Len_Lich)
    Thong_Bao lenLichFrame = new Thong_Bao();

    // Hiển thị JFrame Len_Lich
    lenLichFrame.setVisible(true);

    // Đóng JFrame hiện tại (nếu cần)
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         // Tạo đối tượng JFrame mới (Len_Lich)
    Len_Lich lenLichFrame = new Len_Lich();

    // Hiển thị JFrame Len_Lich
    lenLichFrame.setVisible(true);

    // Đóng JFrame hiện tại (nếu cần)
    this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     // Tạo đối tượng JFrame mới (Len_Lich)
    Chi_Phi lenLichFrame = new Chi_Phi();

    // Hiển thị JFrame Len_Lich
    lenLichFrame.setVisible(true);

    // Đóng JFrame hiện tại (nếu cần)
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     // Tạo đối tượng JFrame mới (Len_Lich)
    Phuong_Tien lenLichFrame = new Phuong_Tien();

    // Hiển thị JFrame Len_Lich
    lenLichFrame.setVisible(true);

    // Đóng JFrame hiện tại (nếu cần)
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
private String getDaLatArticles() {
     return """
    ✨ **Hành trình phiêu lưu tại Đà Lạt** ✨

    Tôi thức dậy giữa làn sương lạnh của Đà Lạt. Hành trình bắt đầu từ những con đường quanh co giữa rừng thông, nơi ánh sáng len lỏi qua những tán cây tạo nên khung cảnh huyền ảo. Tôi quyết định **săn mây tại Đồi chè Cầu Đất**, nơi những làn sương trắng bồng bềnh cuộn quanh từng đồi chè xanh mướt. 

    Khi mặt trời dần lên, tôi rảo bước đến **Hồ Xuân Hương**, nơi tiếng nước lăn tăn hòa cùng những cơn gió nhẹ. Một ly cà phê sữa nóng trên tay, tôi cảm nhận từng hơi thở của thành phố này – bình yên, dịu dàng và thơ mộng. 

    Nhưng Đà Lạt không chỉ là hoa và sương, mà còn là những thử thách. Tôi quyết định trượt máng tại **Thác Datanla**, nơi những khúc cua bất ngờ mang lại cảm giác hồi hộp tột độ. Cuối ngày, tôi thả mình vào không gian lãng mạn tại một **homestay giữa rừng**, nghe tiếng lá rơi lạo xạo trong đêm lạnh.

    🌍 **Cảm nhận**: Đà Lạt như một câu chuyện cổ tích sống động, mỗi góc phố đều chứa đựng một sự bất ngờ. Hành trình của tôi khép lại với một chút tiếc nuối, nhưng tôi biết rằng mình sẽ còn quay lại nơi đây nhiều lần nữa!  
    """;

}
private String getMocChauArticles() {
     return """
    🌿 **Cuộc hành trình khám phá Mộc Châu** 🌿

    Tôi rời khỏi Hà Nội vào một sáng sớm đầy sương. Hành trình đưa tôi qua những cung đường quanh co, nơi những thửa ruộng bậc thang nối tiếp nhau như một bức tranh vẽ bằng màu xanh. Khi đặt chân đến **Đồi chè Trái Tim**, tôi cảm nhận được sự trong lành của núi rừng. Màu xanh bạt ngàn, những luống chè uốn lượn mềm mại như sóng nước.

    Tiếp tục chuyến đi, tôi tìm đến **Thung lũng mận Nà Ka**, nơi từng cơn gió nhẹ làm rung rinh những cành hoa mận trắng. Tôi chụp một vài bức ảnh, cố gắng lưu giữ khoảnh khắc đẹp đẽ của thiên nhiên nơi đây.  

    Khi hoàng hôn buông xuống, tôi ghé **rừng thông Bản Áng**. Cảm giác lạc bước trong khu rừng, nghe tiếng chim líu lo trên từng nhánh cây khiến tôi nhận ra sự bình yên mà thành phố chẳng thể nào có được. 

    🌍 **Cảm nhận**: Mộc Châu không chỉ là một điểm du lịch, nó còn là nơi mang lại sự thư thái trong tâm hồn. Giữa những cánh đồng chè, tôi tìm thấy chính mình – một kẻ lữ hành rong ruổi giữa thiên nhiên bao la.  
    """;

}
private String getSapaArticles() {
  return """
    🏔 **Hành trình khám phá Sa Pa** 🏔

    Sa Pa chào đón tôi với cái lạnh buốt của vùng núi. Tôi bắt đầu ngày mới bằng một tách trà nóng bên hiên nhà gỗ, ngắm nhìn **sương giăng trên những thửa ruộng bậc thang**. Hành trình phiêu lưu chính thức bắt đầu khi tôi quyết định chinh phục **Đỉnh Fansipan**, nơi được mệnh danh là "Nóc nhà Đông Dương". 

    Từ trên cao, nhìn xuống những dãy núi nối tiếp nhau khiến tôi bỗng nhận ra sự hùng vĩ của thiên nhiên. Tôi tiếp tục hành trình đến **Thung lũng Mường Hoa**, nơi có những bản làng nhỏ xinh với nếp nhà gỗ truyền thống. Một cụ già người Dao đỏ mời tôi vào nhà, kể cho tôi nghe những câu chuyện huyền thoại về vùng đất này. 

    Khi màn đêm buông xuống, tôi hòa mình vào phiên chợ vùng cao, nơi người dân tụ họp để trao đổi hàng hóa, những món đặc sản độc đáo của núi rừng. Tôi thử món **thắng cố** – món ăn truyền thống của người H'Mông, có vị béo ngậy và thơm của những loại gia vị đặc trưng.

    🌍 **Cảm nhận**: Sa Pa không chỉ có cảnh đẹp mà còn là nơi giữ gìn văn hóa bản địa. Tôi rời đi với lòng đầy lưu luyến, hẹn một ngày quay trở lại để tiếp tục hành trình khám phá mảnh đất tuyệt vời này.  
    """;

}
    private String getExperienceArticles(String location) {
    if (location.contains("đà lạt")) {
        return getDaLatArticles();
    } else if (location.contains("mộc châu")) {
        return getMocChauArticles();
    } else if (location.contains("sa pa")) {
        return getSapaArticles();
    } else {
        return "Hiện tại chỉ hỗ trợ thông tin cho Đà Lạt, Mộc Châu và Sa Pa.";
    }
}

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 // Lấy dữ liệu từ các trường nhập
    String ten = jTextField2.getText();
    String gmail = jTextField1.getText();
    String diadiem = jTextField3.getText();
    String noidung = jTextArea1.getText();

    // Kiểm tra dữ liệu có bị trống không
    if (ten.isEmpty() || gmail.isEmpty() || diadiem.isEmpty() || noidung.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Kết nối và gửi dữ liệu lên MySQL
    try {
        // Đăng ký MySQL JDBC Driver trước khi kết nối
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Cấu hình kết nối MySQL theo thông tin phpMyAdmin
        String url = "jdbc:mysql://localhost:3306/travelandmap?serverTimezone=UTC";
        String user = "root";  // Nếu bạn có tài khoản khác, thay thế tại đây
        String password = "";  // Nếu không có mật khẩu, để trống

        // Kết nối đến MySQL
        java.sql.Connection conn = DriverManager.getConnection(url, user, password);
        System.out.println("Kết nối thành công với MySQL!");

        // Câu SQL INSERT để thêm dữ liệu vào bảng `newdata`
        String sql = "INSERT INTO newdata (Ten, gmail, diadiem, noidung) VALUES (?, ?, ?, ?)";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, ten);
        pstmt.setString(2, gmail);
        pstmt.setString(3, diadiem);
        pstmt.setString(4, noidung);

        // Thực thi câu lệnh
        int rowsAffected = pstmt.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Chúng Tôi Đã Nhận Được Bài Viết Của Bạn, Cảm Ơn Bạn Đã chia Sẻ !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Gửi dữ liệu thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

        // Đóng kết nối
        pstmt.close();
        conn.close();
    } catch (ClassNotFoundException e) {
        JOptionPane.showMessageDialog(null, "Không tìm thấy MySQL JDBC Driver! Kiểm tra lại thư viện.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Không thể kết nối đến MySQL! Kiểm tra lại thông tin đăng nhập hoặc máy chủ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Home dk = new Home();
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chia_Se.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chia_Se.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chia_Se.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chia_Se.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chia_Se().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
