/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FE;

/**
 *
 * @author DUY NGUYEN
 */
public class Thong_Bao extends javax.swing.JFrame {

    /**
     * Creates new form Trip_planner
     */
    public Thong_Bao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Tìm kiếm và gợi ý");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 140, 40));

        jButton2.setText("Chia sẻ lịch trình");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 220, 180, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Khám phá thế giới, bắt đầu từ đây");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 567, 65));

        jButton3.setText("Thông báo và nhắc nhở");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 170, 40));

        jButton4.setText("Lên lịch chuyến đi ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 40));

        jButton5.setText("Tính năng tính chi phí");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, -1, 40));

        jButton6.setText("Quản lý phương tiện di chuyển ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 200, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TRAVEL AND MAP");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 180, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Trip Planner - Người bạn đồng hành lý tưởng cho mọi hành trình!");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 565, 81));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 90, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hãy nhập địa điểm mà bạn sẽ du lịch:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 210, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nhập tháng mà bạn sẽ đi du lịch:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Đây là những thông tin mà chúng tôi muốn gửi đến bạn:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 560, 230));

        jButton7.setText("Xác nhận");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Home");
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, 100, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(1300, 700));
        jLabel6.setMinimumSize(new java.awt.Dimension(1300, 700));
        jLabel6.setPreferredSize(new java.awt.Dimension(1300, 700));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 // Tạo đối tượng JFrame mới (Len_Lich)
    Chia_Se lenLichFrame = new Chia_Se();

    // Hiển thị JFrame Len_Lich
    lenLichFrame.setVisible(true);

    // Đóng JFrame hiện tại (nếu cần)
    this.dispose();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             // Tạo đối tượng JFrame mới (Len_Lich)
    Tim_Kiem lenLichFrame = new Tim_Kiem();

    // Hiển thị JFrame Len_Lich
    lenLichFrame.setVisible(true);

    // Đóng JFrame hiện tại (nếu cần)
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         // Tạo đối tượng JFrame mới (Len_Lich)
    Len_Lich lenLichFrame = new Len_Lich();

    // Hiển thị JFrame Len_Lich
    lenLichFrame.setVisible(true);

    // Đóng JFrame hiện tại (nếu cần)
    this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     // Tạo đối tượng JFrame mới (Len_Lich)
    Chi_Phi lenLichFrame = new Chi_Phi();

    // Hiển thị JFrame Len_Lich
    lenLichFrame.setVisible(true);

    // Đóng JFrame hiện tại (nếu cần)
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     // Tạo đối tượng JFrame mới (Len_Lich)
    Phuong_Tien lenLichFrame = new Phuong_Tien();

    // Hiển thị JFrame Len_Lich
    lenLichFrame.setVisible(true);

    // Đóng JFrame hiện tại (nếu cần)
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
private String getDaLatInfo(int month) {
    switch (month) {
        case 1:
            return "Tháng 1 - Đà Lạt mùa mai anh đào rực rỡ.\nThời tiết: Se lạnh, ít mưa.\nNên đi: Hồ Xuân Hương - Trung tâm Đà Lạt, cung đường mai anh đào - Đường Trần Hưng Đạo.\nPhương tiện: Máy bay, xe khách.";
        case 2:
            return "Tháng 2 - Đà Lạt mùa hoa ban trắng.\nThời tiết: Mát mẻ, ít mưa.\nNên đi: Đồi chè Cầu Đất - Thôn Trường Thọ, Xã Trạm Hành, TP. Đà Lạt, vườn dâu Biofresh - Số 17 Vòng Lâm Viên, Phường 8.\nPhương tiện: Xe khách, ô tô riêng.";
        case 3:
            return "Tháng 3 - Đà Lạt lãng mạn với hoa phượng tím.\nThời tiết: Dịu mát, có nắng nhẹ.\nNên đi: Hồ Tuyền Lâm - Phường 4, Nhà thờ Con Gà - Số 15 Trần Phú.\nPhương tiện: Xe máy, taxi.";
        case 4:
            return "Tháng 4 - Đà Lạt nắng ấm, mây xanh.\nThời tiết: Ổn định, ít mưa.\nNên đi: Thung lũng Tình Yêu - Số 05 – 07 Mai Anh Đào, Langbiang - Thị trấn Lạc Dương.\nPhương tiện: Xe khách, ô tô.";
        case 5:
            return "Tháng 5 - Đà Lạt bắt đầu mùa mưa.\nThời tiết: Mưa nhẹ, mát mẻ.\nNên đi: Nhà thờ Con Gà - Số 15 Trần Phú, vườn hoa thành phố - Đường Trần Quốc Toản.\nPhương tiện: Xe máy, taxi.";
        case 6:
            return "Tháng 6 - Đà Lạt mùa trái cây.\nThời tiết: Mưa nhiều, trời mát.\nNên đi: Vườn dâu Biofresh - Số 17 Vòng Lâm Viên, vườn hồng Đà Lạt - Xã Tà Nung.\nPhương tiện: Xe khách, ô tô.";
        case 7:
            return "Tháng 7 - Đà Lạt ngày mưa lãng mạn.\nThời tiết: Mưa nhiều, se lạnh.\nNên đi: Quán Café Mê Linh - Tổ 20, Thôn 4, Xã Tà Nung, hồ Xuân Hương - Trung tâm Đà Lạt.\nPhương tiện: Xe máy, taxi.";
        case 8:
            return "Tháng 8 - Đà Lạt vào mùa săn mây.\nThời tiết: Mát mẻ, có sương mù.\nNên đi: Đồi chè Cầu Đất - Thôn Trường Thọ, Xã Trạm Hành, đỉnh Pinhatt - Khu vực Hồ Tuyền Lâm.\nPhương tiện: Xe khách, ô tô.";
        case 9:
            return "Tháng 9 - Đà Lạt những ngày giao mùa.\nThời tiết: Ít mưa, trời đẹp.\nNên đi: Hồ Tuyền Lâm - Phường 4, vườn hoa thành phố - Đường Trần Quốc Toản.\nPhương tiện: Xe máy, taxi.";
        case 10:
            return "Tháng 10 - Đà Lạt mùa hoa dã quỳ.\nThời tiết: Mát mẻ, ít mưa.\nNên đi: Đồi hoa dã quỳ - Đèo Prenn, Làng Cù Lần - Xã Lát, Huyện Lạc Dương.\nPhương tiện: Xe khách, ô tô.";
        case 11:
            return "Tháng 11 - Đà Lạt vào đông.\nThời tiết: Se lạnh, có sương mù.\nNên đi: Hồ Xuân Hương - Trung tâm Đà Lạt, vườn hồng Đà Lạt - Xã Tà Nung.\nPhương tiện: Xe máy, taxi.";
        case 12:
            return "Tháng 12 - Đà Lạt mùa lễ hội.\nThời tiết: Lạnh, có sương mù.\nNên đi: Chợ đêm Đà Lạt - Đường Nguyễn Thị Minh Khai, quảng trường Lâm Viên - Đường Trần Quốc Toản.\nPhương tiện: Xe khách, ô tô.";
        default:
            return "Tháng không hợp lệ.";

    }
}
private String getMocChauInfo(int month) {
    switch (month) {
        case 1:
            return "Tháng 1 - Mộc Châu mùa hoa cải trắng.\nThời tiết: Lạnh, sương mù nhẹ.\nNên đi: Rừng thông Bản Áng - Xã Đông Sang, đồi chè Mộc Châu - Thị trấn Nông Trường.\nPhương tiện: Xe khách, xe máy.";
        case 2:
            return "Tháng 2 - Mộc Châu mùa mận nở trắng trời.\nThời tiết: Mát mẻ, trời trong.\nNên đi: Thung lũng mận Nà Ka - Xã Tân Lập, Hang Dơi - Thị trấn Mộc Châu.\nPhương tiện: Xe khách, ô tô cá nhân.";
        case 3:
            return "Tháng 3 - Mùa ban trắng Tây Bắc.\nThời tiết: Mát, có nắng nhẹ.\nNên đi: Đèo Pha Luông - Xã Chiềng Sơn, vườn hoa nhiệt đới Mộc Châu.\nPhương tiện: Xe máy, xe khách.";
        case 4:
            return "Tháng 4 - Mộc Châu mát mẻ.\nThời tiết: Ôn hòa, ít mưa.\nNên đi: Khu du lịch Ngũ Động - Bản Ôn, Trang trại bò sữa Mộc Châu.\nPhương tiện: Ô tô riêng, xe khách.";
        case 5:
            return "Tháng 5 - Bước vào mùa mận chín.\nThời tiết: Mát, thỉnh thoảng có mưa nhẹ.\nNên đi: Thung lũng mận Nà Ka - Xã Tân Lập, Rừng thông Bản Áng - Xã Đông Sang.\nPhương tiện: Xe khách, xe máy.";
        case 6:
            return "Tháng 6 - Mộc Châu mùa hè.\nThời tiết: Ấm áp, có nắng.\nNên đi: Thác Dải Yếm - Xã Mường Sang, Đồi chè trái tim - Thị trấn Nông Trường.\nPhương tiện: Xe khách, ô tô.";
        case 7:
            return "Tháng 7 - Khí hậu mát mẻ.\nThời tiết: Mưa nhiều, mát.\nNên đi: Hồ bản Áng - Xã Đông Sang, Khu du lịch Ngũ Động - Bản Ôn.\nPhương tiện: Xe khách, xe máy.";
        case 8:
            return "Tháng 8 - Khám phá Tây Bắc.\nThời tiết: Ôn hòa, nắng nhẹ.\nNên đi: Đèo Pha Luông - Xã Chiềng Sơn, Hang Dơi - Thị trấn Mộc Châu.\nPhương tiện: Xe máy, ô tô.";
        case 9:
            return "Tháng 9 - Mộc Châu mùa lúa chín.\nThời tiết: Khô ráo, trời đẹp.\nNên đi: Bản Thái Hưng - Xã Mường Sang, Đồi chè Mộc Châu - Thị trấn Nông Trường.\nPhương tiện: Xe khách, ô tô.";
        case 10:
            return "Tháng 10 - Mùa hoa cải trắng.\nThời tiết: Se lạnh, ít mưa.\nNên đi: Rừng thông Bản Áng - Xã Đông Sang, Thác Dải Yếm - Xã Mường Sang.\nPhương tiện: Xe khách, xe máy.";
        case 11:
            return "Tháng 11 - Cao nguyên xanh mát.\nThời tiết: Lạnh, có sương mù.\nNên đi: Thung lũng hoa cải - Xã Đông Sang, Đèo Pha Luông - Xã Chiềng Sơn.\nPhương tiện: Xe máy, ô tô.";
        case 12:
            return "Tháng 12 - Mộc Châu những ngày đông.\nThời tiết: Rét, có sương mù.\nNên đi: Rừng thông Bản Áng - Xã Đông Sang, Đồi chè trái tim - Thị trấn Nông Trường.\nPhương tiện: Xe khách, ô tô.";
        default:
            return "Tháng không hợp lệ.";
    }
}
private String getSapaInfo(int month) {
    switch (month) {
        case 1:
            return "Tháng 1 - Sa Pa mùa đông.\nThời tiết: Lạnh, có thể có băng tuyết.\nNên đi: Đỉnh Fansipan - Khu du lịch Sun World Fansipan Legend, Nhà thờ đá - Trung tâm thị trấn.\nPhương tiện: Xe khách, tàu hỏa.";
        case 2:
            return "Tháng 2 - Hoa đào nở rộ.\nThời tiết: Lạnh, ít mưa.\nNên đi: Bản Cát Cát - Xã San Sả Hồ, Đèo Ô Quy Hồ - Quốc lộ 4D.\nPhương tiện: Xe khách, ô tô riêng.";
        case 3:
            return "Tháng 3 - Khí hậu ôn hòa.\nThời tiết: Mát mẻ, trời đẹp.\nNên đi: Núi Hàm Rồng - Trung tâm thị trấn, Thung lũng Mường Hoa - Xã Hầu Thào.\nPhương tiện: Xe máy, ô tô.";
        case 4:
            return "Tháng 4 - Mùa hoa đỗ quyên.\nThời tiết: Ôn hòa, ít mưa.\nNên đi: Đỉnh Fansipan - Khu du lịch Sun World Fansipan Legend, Bản Tả Van - Xã Tả Van.\nPhương tiện: Xe khách, tàu hỏa.";
        case 5:
            return "Tháng 5 - Ruộng bậc thang xanh rì.\nThời tiết: Mát mẻ, có nắng nhẹ.\nNên đi: Bản Lao Chải - Xã Lao Chải, Núi Hàm Rồng - Trung tâm thị trấn.\nPhương tiện: Xe máy, ô tô.";
        case 6:
            return "Tháng 6 - Khí hậu dễ chịu.\nThời tiết: Mát, có mưa nhỏ.\nNên đi: Thung lũng Mường Hoa - Xã Hầu Thào, Bản Sín Chải - Xã Sín Chải.\nPhương tiện: Xe khách, xe máy.";
        case 7:
            return "Tháng 7 - Mùa mưa Sa Pa.\nThời tiết: Mưa nhiều, có sương mù.\nNên đi: Bản Tả Phìn - Xã Tả Phìn, Nhà thờ đá - Trung tâm thị trấn.\nPhương tiện: Ô tô, tàu hỏa.";
        case 8:
            return "Tháng 8 - Khám phá bản làng.\nThời tiết: Mát, ít mưa.\nNên đi: Bản Lao Chải - Xã Lao Chải, Đèo Ô Quy Hồ - Quốc lộ 4D.\nPhương tiện: Xe khách, ô tô.";
        case 9:
            return "Tháng 9 - Mùa lúa chín vàng.\nThời tiết: Ôn hòa, trời đẹp.\nNên đi: Bản Tả Van - Xã Tả Van, Núi Hàm Rồng - Trung tâm thị trấn.\nPhương tiện: Xe máy, xe khách.";
        case 10:
            return "Tháng 10 - Sa Pa mùa thu.\nThời tiết: Se lạnh, ít mưa.\nNên đi: Bản Cát Cát - Xã San Sả Hồ, Đỉnh Fansipan - Khu du lịch Sun World Fansipan Legend.\nPhương tiện: Xe khách, tàu hỏa.";
        case 11:
            return "Tháng 11 - Mùa săn mây.\nThời tiết: Lạnh, sương mù nhiều.\nNên đi: Đèo Ô Quy Hồ - Quốc lộ 4D, Bản Tả Phìn - Xã Tả Phìn.\nPhương tiện: Xe máy, ô tô.";
        case 12:
            return "Tháng 12 - Sa Pa mùa đông.\nThời tiết: Rét đậm, có thể có tuyết.\nNên đi: Đỉnh Fansipan - Khu du lịch Sun World Fansipan Legend, Nhà thờ đá - Trung tâm thị trấn.\nPhương tiện: Xe khách, tàu hỏa.";
        default:
            return "Tháng không hợp lệ.";
    }
}

    private String getTravelInfo(String location, int month) {
     if (location.contains("đà lạt")) {
        return getDaLatInfo(month);
    } else if (location.contains("mộc châu")) {
        return getMocChauInfo(month);
    } else if (location.contains("sapa")) {
        return getSapaInfo(month);
    } else {
        return "Hiện tại chỉ hỗ trợ thông tin cho Đà Lạt, Mộc Châu và Sa Pa.";
    }

}

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         String location = jTextField1.getText().toLowerCase();
    int month = jComboBox1.getSelectedIndex() + 1; // Lấy tháng từ ComboBox

    String result = getTravelInfo(location, month);
    jTextArea2.setText(result); // Hiển thị thông tin trên JTextArea2

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Home dk = new Home();
        dk.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thong_Bao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thong_Bao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thong_Bao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thong_Bao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Thong_Bao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
