/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FE;

/**
 *
 * @author PC
 */
public class ThongTinKH4 extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinKH4
     */
    public ThongTinKH4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Ten_Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        btn_language = new javax.swing.JButton();
        btn_aboutUs = new javax.swing.JButton();
        btn_contact1 = new javax.swing.JButton();
        btn_explore = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ten_Logo.setFont(new java.awt.Font("Vivaldi", 1, 35)); // NOI18N
        Ten_Logo.setText("Travel and Map");
        jPanel1.add(Ten_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOUR BOOKING – Payment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1300, -1));

        btn_home.setBackground(new java.awt.Color(0, 102, 102));
        btn_home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setText("Home");
        btn_home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_home.setBorderPainted(false);
        btn_home.setContentAreaFilled(false);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, 60));

        btn_language.setBackground(new java.awt.Color(0, 102, 102));
        btn_language.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_language.setForeground(new java.awt.Color(255, 255, 255));
        btn_language.setText("Language");
        btn_language.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_language.setBorderPainted(false);
        btn_language.setContentAreaFilled(false);
        btn_language.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_languageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_language, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, 70));

        btn_aboutUs.setBackground(new java.awt.Color(0, 102, 102));
        btn_aboutUs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_aboutUs.setForeground(new java.awt.Color(255, 255, 255));
        btn_aboutUs.setText("About Us");
        btn_aboutUs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_aboutUs.setBorderPainted(false);
        btn_aboutUs.setContentAreaFilled(false);
        btn_aboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutUsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_aboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, 70));

        btn_contact1.setBackground(new java.awt.Color(0, 102, 102));
        btn_contact1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_contact1.setForeground(new java.awt.Color(255, 255, 255));
        btn_contact1.setText("Contact");
        btn_contact1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_contact1.setBorderPainted(false);
        btn_contact1.setContentAreaFilled(false);
        btn_contact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contact1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, -1, 70));

        btn_explore.setBackground(new java.awt.Color(0, 0, 0));
        btn_explore.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_explore.setForeground(new java.awt.Color(255, 255, 255));
        btn_explore.setText("Explore");
        btn_explore.setBorder(null);
        btn_explore.setContentAreaFilled(false);
        btn_explore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exploreActionPerformed(evt);
            }
        });
        jPanel1.add(btn_explore, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 97, 68));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background_Home.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 270));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/check-6380867_640 (2).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 290, 250));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Payment successful");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        Home dk = new Home();
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_languageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_languageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_languageActionPerformed

    private void btn_aboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aboutUsActionPerformed

    private void btn_contact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_contact1ActionPerformed

    private void btn_exploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exploreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_exploreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home dk = new Home();
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinKH4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinKH4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinKH4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinKH4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinKH4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ten_Logo;
    private javax.swing.JButton btn_aboutUs;
    private javax.swing.JButton btn_contact1;
    private javax.swing.JButton btn_explore;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_language;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
