/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FE;


import BE.MySQLConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;



/**
 *
 * @author PC
 */
public class TienTe extends javax.swing.JFrame {
private DefaultListModel<String> listModel = new DefaultListModel<>();




    /**
     * Creates new form TienTe
     */
    public TienTe() {
    initComponents();
    lichsu.setModel(listModel);
    loadConversionsToList(); // Tải dữ liệu ngay khi mở form
}

    public void loadConversionsToList() {
    listModel.clear(); // Xóa dữ liệu cũ trước khi tải dữ liệu mới

    try (Connection conn = MySQLConnection.getConnection()) {
        String sql = "SELECT amount, from_currency, to_currency, result FROM conversions ORDER BY converted_at DESC LIMIT 10";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            double amount = rs.getDouble("amount");
            String fromCurrency = rs.getString("from_currency");
            String toCurrency = rs.getString("to_currency");
            double result = rs.getDouble("result");

            // Thêm kết quả vào JList
            String display = String.format("%.2f %s → %.2f %s", amount, fromCurrency, result, toCurrency);
            listModel.addElement(display);
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Ten_Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lichsu = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        fromCurrency = new javax.swing.JComboBox<>();
        toCurrency = new javax.swing.JComboBox<>();
        convertButton = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        btn_language = new javax.swing.JButton();
        btn_aboutUs = new javax.swing.JButton();
        btn_contact1 = new javax.swing.JButton();
        btn_explore = new javax.swing.JButton();
        btn_SignUp1 = new javax.swing.JButton();
        btn_LogIn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        resultLabel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1300, 1000));

        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 1500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ten_Logo.setFont(new java.awt.Font("Vivaldi", 1, 35)); // NOI18N
        Ten_Logo.setText("Travel and Map");
        jPanel1.add(Ten_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quick and Easy Currency Exchange");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1300, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Just enter the amount and select the currency you want to convert. The result will be displayed instantly.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1300, -1));

        jScrollPane2.setViewportView(lichsu);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 640, 330, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("The amount of money:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 210, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Currency:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 210, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Currency song:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 210, 20));

        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });
        jPanel1.add(amountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 330, 30));

        fromCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "VND", "EUR", "JPY" }));
        fromCurrency.setAutoscrolls(true);
        fromCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromCurrencyActionPerformed(evt);
            }
        });
        jPanel1.add(fromCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 330, 30));

        toCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "VND", "EUR", "JPY" }));
        jPanel1.add(toCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 330, 30));

        convertButton.setBackground(new java.awt.Color(255, 102, 51));
        convertButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        convertButton.setForeground(new java.awt.Color(255, 255, 255));
        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });
        jPanel1.add(convertButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 110, 30));

        btn_home.setBackground(new java.awt.Color(0, 102, 102));
        btn_home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setText("Home");
        btn_home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_home.setBorderPainted(false);
        btn_home.setContentAreaFilled(false);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, 60));

        btn_language.setBackground(new java.awt.Color(0, 102, 102));
        btn_language.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_language.setForeground(new java.awt.Color(255, 255, 255));
        btn_language.setText("Language");
        btn_language.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_language.setBorderPainted(false);
        btn_language.setContentAreaFilled(false);
        btn_language.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_languageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_language, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, 70));

        btn_aboutUs.setBackground(new java.awt.Color(0, 102, 102));
        btn_aboutUs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_aboutUs.setForeground(new java.awt.Color(255, 255, 255));
        btn_aboutUs.setText("About Us");
        btn_aboutUs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_aboutUs.setBorderPainted(false);
        btn_aboutUs.setContentAreaFilled(false);
        btn_aboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutUsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_aboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, 70));

        btn_contact1.setBackground(new java.awt.Color(0, 102, 102));
        btn_contact1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_contact1.setForeground(new java.awt.Color(255, 255, 255));
        btn_contact1.setText("Contact");
        btn_contact1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_contact1.setBorderPainted(false);
        btn_contact1.setContentAreaFilled(false);
        btn_contact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contact1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, -1, 70));

        btn_explore.setBackground(new java.awt.Color(0, 0, 0));
        btn_explore.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_explore.setForeground(new java.awt.Color(255, 255, 255));
        btn_explore.setText("Explore");
        btn_explore.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_explore.setContentAreaFilled(false);
        btn_explore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exploreActionPerformed(evt);
            }
        });
        jPanel1.add(btn_explore, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 97, 68));

        btn_SignUp1.setBackground(new java.awt.Color(0, 102, 102));
        btn_SignUp1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_SignUp1.setForeground(new java.awt.Color(255, 255, 255));
        btn_SignUp1.setText("Sign Up");
        btn_SignUp1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_SignUp1.setBorderPainted(false);
        btn_SignUp1.setContentAreaFilled(false);
        btn_SignUp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignUp1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_SignUp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, -1, 63));

        btn_LogIn.setBackground(new java.awt.Color(0, 102, 102));
        btn_LogIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_LogIn.setForeground(new java.awt.Color(255, 255, 255));
        btn_LogIn.setText("Log in");
        btn_LogIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_LogIn.setBorderPainted(false);
        btn_LogIn.setContentAreaFilled(false);
        btn_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogInActionPerformed(evt);
            }
        });
        jPanel1.add(btn_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 50, -1, 63));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(resultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 330, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Screenshot 2025-04-27 081230.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 810, 580));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1310, 690));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background_Home.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 320));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 1320, 1020));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        Home dk = new Home();

        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_languageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_languageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_languageActionPerformed

    private void btn_aboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aboutUsActionPerformed

    private void btn_contact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_contact1ActionPerformed

    private void btn_exploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exploreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_exploreActionPerformed

    private void btn_SignUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignUp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SignUp1ActionPerformed

    private void btn_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LogInActionPerformed

    private void fromCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromCurrencyActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed

     try {
    double amount = Double.parseDouble(amountField.getText().trim());
    String from = (String) fromCurrency.getSelectedItem();
    String to = (String) toCurrency.getSelectedItem();

    if (from.equals(to)) {
        resultLabel.setText("Please choose two different currencies.");
        return;
    }

    // Convert to USD first
    double usdAmount;
    switch (from) {
        case "USD": usdAmount = amount; break;
        case "VND": usdAmount = amount / 25000; break;
        case "EUR": usdAmount = amount / 0.85; break;
        case "JPY": usdAmount = amount / 110.0; break;
        default:
            resultLabel.setText("Unsupported currency type: " + from);
            return;
    }

    // Convert from USD to the target currency
    double result;
    switch (to) {
        case "USD": result = usdAmount; break;
        case "VND": result = usdAmount * 25000; break;
        case "EUR": result = usdAmount * 0.85; break;
        case "JPY": result = usdAmount * 110.0; break;
        default:
            resultLabel.setText("Unsupported currency type: " + to);
            return;
    }

    // Display the result
    resultLabel.setText(String.format("Result: %.2f %s = %.2f %s", amount, from, result, to));

    // Save to MySQL
    String sql = "INSERT INTO conversions (amount, from_currency, to_currency, result) VALUES (?, ?, ?, ?)";

    try (Connection conn = MySQLConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setDouble(1, amount);
        ps.setString(2, from);
        ps.setString(3, to);
        ps.setDouble(4, result);

        int rowsInserted = ps.executeUpdate();
        if (rowsInserted > 0) {
            System.out.println("✅ Successfully saved to MySQL.");
        } else {
            System.out.println("⚠️ Failed to save to MySQL.");
        }

    } catch (SQLException e) {
        System.err.println("❌ Error connecting to or saving to MySQL:");
        e.printStackTrace();
        resultLabel.setText("Error saving result to database.");
    }

    // Update the JList
    loadConversionsToList();

} catch (NumberFormatException ex) {
    resultLabel.setText("❌ Please enter a valid number!");
}



    }//GEN-LAST:event_convertButtonActionPerformed

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TienTe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TienTe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TienTe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TienTe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TienTe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ten_Logo;
    private javax.swing.JTextField amountField;
    private javax.swing.JButton btn_LogIn;
    private javax.swing.JButton btn_SignUp1;
    private javax.swing.JButton btn_aboutUs;
    private javax.swing.JButton btn_contact1;
    private javax.swing.JButton btn_explore;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_language;
    private javax.swing.JButton convertButton;
    private javax.swing.JComboBox<String> fromCurrency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lichsu;
    private javax.swing.JTextField resultLabel;
    private javax.swing.JComboBox<String> toCurrency;
    // End of variables declaration//GEN-END:variables
}
